// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	"github.com/swaggo/swag"
	"go-tel/src/backbone/api"
	"go-tel/src/backbone/service_layer"
)

var DocTemplate = addSwagger()

func addSwagger() string {
	e := service_layer.NewAPIRouter(true)
	api.InitRoute(e.Group("/api"))
	swaggerDoc := service_layer.AddSwaggerDoc()
	return swaggerDoc
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AliProject",
	Description:      "This is a sample AliProject.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  DocTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
